package com.chinapay.cip.model;

import java.util.Date;

/**
 * 
 */
public class AppUser {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.USERID
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private Long USERID;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.AGREEMENT_NUM
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private String AGREEMENT_NUM;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.MERCODE
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private String MERCODE;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.CUST_CODE
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private String CUST_CODE;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.USERNAME
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private String USERNAME;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.PASSWORD
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private String PASSWORD;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.EMAIL
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private String EMAIL;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.MOBILE
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private String MOBILE;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.FULLNAME
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private String FULLNAME;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.DELFLAG
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private Integer DELFLAG;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.USERTYPE
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private String USERTYPE;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.TRADEPWD
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private String TRADEPWD;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.LOGINPWDERR
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private Integer LOGINPWDERR;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.TRADEPWDERR
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private Integer TRADEPWDERR;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.LOGINPWDLOCK
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private Integer LOGINPWDLOCK;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.TRADEPWDLOCK
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private Integer TRADEPWDLOCK;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.SESSIONID
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private String SESSIONID;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.IMEI
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private String IMEI;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.IMSI
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private String IMSI;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.MACADDRESS
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private String MACADDRESS;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.APPNAME
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private String APPNAME;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.VERSIONCODE
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private String VERSIONCODE;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.OSTYPE
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private String OSTYPE;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.IPADDRESS
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private String IPADDRESS;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.CREATE_DATE
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private Date CREATE_DATE;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.LASTLOGIN
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private Date LASTLOGIN;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.STATUS
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private String STATUS;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.NICK_NAME
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private String NICK_NAME;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.MOD_TIME
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private Date MOD_TIME;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database column CPMOMS.APP_USER.OPERUSER
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	private String OPERUSER;
	/**
	 * .
	 */
    private String MERSUBID;
    /**
     * @return String String
     */
	public String getMERSUBID() {
	return MERSUBID;
     }
      /** 
       * @param mERSUBID mERSUBID
       */
    public void setMERSUBID(String mERSUBID) {
	MERSUBID = mERSUBID;
     }

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.USERID
	 * @return  the value of CPMOMS.APP_USER.USERID
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public Long getUSERID() {
		return USERID;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.USERID
	 * @param USERID  the value for CPMOMS.APP_USER.USERID
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setUSERID(Long USERID) {
		this.USERID = USERID;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.AGREEMENT_NUM
	 * @return  the value of CPMOMS.APP_USER.AGREEMENT_NUM
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public String getAGREEMENT_NUM() {
		return AGREEMENT_NUM;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.AGREEMENT_NUM
	 * @param AGREEMENT_NUM  the value for CPMOMS.APP_USER.AGREEMENT_NUM
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setAGREEMENT_NUM(String AGREEMENT_NUM) {
		this.AGREEMENT_NUM = AGREEMENT_NUM == null ? null : AGREEMENT_NUM.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.MERCODE
	 * @return  the value of CPMOMS.APP_USER.MERCODE
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public String getMERCODE() {
		return MERCODE;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.MERCODE
	 * @param MERCODE  the value for CPMOMS.APP_USER.MERCODE
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setMERCODE(String MERCODE) {
		this.MERCODE = MERCODE == null ? null : MERCODE.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.CUST_CODE
	 * @return  the value of CPMOMS.APP_USER.CUST_CODE
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public String getCUST_CODE() {
		return CUST_CODE;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.CUST_CODE
	 * @param CUST_CODE  the value for CPMOMS.APP_USER.CUST_CODE
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setCUST_CODE(String CUST_CODE) {
		this.CUST_CODE = CUST_CODE == null ? null : CUST_CODE.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.USERNAME
	 * @return  the value of CPMOMS.APP_USER.USERNAME
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public String getUSERNAME() {
		return USERNAME;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.USERNAME
	 * @param USERNAME  the value for CPMOMS.APP_USER.USERNAME
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setUSERNAME(String USERNAME) {
		this.USERNAME = USERNAME == null ? null : USERNAME.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.PASSWORD
	 * @return  the value of CPMOMS.APP_USER.PASSWORD
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public String getPASSWORD() {
		return PASSWORD;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.PASSWORD
	 * @param PASSWORD  the value for CPMOMS.APP_USER.PASSWORD
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setPASSWORD(String PASSWORD) {
		this.PASSWORD = PASSWORD == null ? null : PASSWORD.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.EMAIL
	 * @return  the value of CPMOMS.APP_USER.EMAIL
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public String getEMAIL() {
		return EMAIL;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.EMAIL
	 * @param EMAIL  the value for CPMOMS.APP_USER.EMAIL
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setEMAIL(String EMAIL) {
		this.EMAIL = EMAIL == null ? null : EMAIL.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.MOBILE
	 * @return  the value of CPMOMS.APP_USER.MOBILE
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public String getMOBILE() {
		return MOBILE;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.MOBILE
	 * @param MOBILE  the value for CPMOMS.APP_USER.MOBILE
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setMOBILE(String MOBILE) {
		this.MOBILE = MOBILE == null ? null : MOBILE.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.FULLNAME
	 * @return  the value of CPMOMS.APP_USER.FULLNAME
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public String getFULLNAME() {
		return FULLNAME;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.FULLNAME
	 * @param FULLNAME  the value for CPMOMS.APP_USER.FULLNAME
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setFULLNAME(String FULLNAME) {
		this.FULLNAME = FULLNAME == null ? null : FULLNAME.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.DELFLAG
	 * @return  the value of CPMOMS.APP_USER.DELFLAG
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public Integer getDELFLAG() {
		return DELFLAG;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.DELFLAG
	 * @param DELFLAG  the value for CPMOMS.APP_USER.DELFLAG
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setDELFLAG(Integer DELFLAG) {
		this.DELFLAG = DELFLAG;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.USERTYPE
	 * @return  the value of CPMOMS.APP_USER.USERTYPE
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public String getUSERTYPE() {
		return USERTYPE;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.USERTYPE
	 * @param USERTYPE  the value for CPMOMS.APP_USER.USERTYPE
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setUSERTYPE(String USERTYPE) {
		this.USERTYPE = USERTYPE == null ? null : USERTYPE.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.TRADEPWD
	 * @return  the value of CPMOMS.APP_USER.TRADEPWD
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public String getTRADEPWD() {
		return TRADEPWD;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.TRADEPWD
	 * @param TRADEPWD  the value for CPMOMS.APP_USER.TRADEPWD
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setTRADEPWD(String TRADEPWD) {
		this.TRADEPWD = TRADEPWD == null ? null : TRADEPWD.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.LOGINPWDERR
	 * @return  the value of CPMOMS.APP_USER.LOGINPWDERR
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public Integer getLOGINPWDERR() {
		return LOGINPWDERR;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.LOGINPWDERR
	 * @param LOGINPWDERR  the value for CPMOMS.APP_USER.LOGINPWDERR
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setLOGINPWDERR(Integer LOGINPWDERR) {
		this.LOGINPWDERR = LOGINPWDERR;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.TRADEPWDERR
	 * @return  the value of CPMOMS.APP_USER.TRADEPWDERR
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public Integer getTRADEPWDERR() {
		return TRADEPWDERR;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.TRADEPWDERR
	 * @param TRADEPWDERR  the value for CPMOMS.APP_USER.TRADEPWDERR
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setTRADEPWDERR(Integer TRADEPWDERR) {
		this.TRADEPWDERR = TRADEPWDERR;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.LOGINPWDLOCK
	 * @return  the value of CPMOMS.APP_USER.LOGINPWDLOCK
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public Integer getLOGINPWDLOCK() {
		return LOGINPWDLOCK;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.LOGINPWDLOCK
	 * @param LOGINPWDLOCK  the value for CPMOMS.APP_USER.LOGINPWDLOCK
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setLOGINPWDLOCK(Integer LOGINPWDLOCK) {
		this.LOGINPWDLOCK = LOGINPWDLOCK;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.TRADEPWDLOCK
	 * @return  the value of CPMOMS.APP_USER.TRADEPWDLOCK
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public Integer getTRADEPWDLOCK() {
		return TRADEPWDLOCK;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.TRADEPWDLOCK
	 * @param TRADEPWDLOCK  the value for CPMOMS.APP_USER.TRADEPWDLOCK
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setTRADEPWDLOCK(Integer TRADEPWDLOCK) {
		this.TRADEPWDLOCK = TRADEPWDLOCK;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.SESSIONID
	 * @return  the value of CPMOMS.APP_USER.SESSIONID
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public String getSESSIONID() {
		return SESSIONID;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.SESSIONID
	 * @param SESSIONID  the value for CPMOMS.APP_USER.SESSIONID
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setSESSIONID(String SESSIONID) {
		this.SESSIONID = SESSIONID == null ? null : SESSIONID.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.IMEI
	 * @return  the value of CPMOMS.APP_USER.IMEI
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public String getIMEI() {
		return IMEI;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.IMEI
	 * @param IMEI  the value for CPMOMS.APP_USER.IMEI
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setIMEI(String IMEI) {
		this.IMEI = IMEI == null ? null : IMEI.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.IMSI
	 * @return  the value of CPMOMS.APP_USER.IMSI
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public String getIMSI() {
		return IMSI;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.IMSI
	 * @param IMSI  the value for CPMOMS.APP_USER.IMSI
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setIMSI(String IMSI) {
		this.IMSI = IMSI == null ? null : IMSI.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.MACADDRESS
	 * @return  the value of CPMOMS.APP_USER.MACADDRESS
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public String getMACADDRESS() {
		return MACADDRESS;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.MACADDRESS
	 * @param MACADDRESS  the value for CPMOMS.APP_USER.MACADDRESS
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setMACADDRESS(String MACADDRESS) {
		this.MACADDRESS = MACADDRESS == null ? null : MACADDRESS.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.APPNAME
	 * @return  the value of CPMOMS.APP_USER.APPNAME
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public String getAPPNAME() {
		return APPNAME;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.APPNAME
	 * @param APPNAME  the value for CPMOMS.APP_USER.APPNAME
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setAPPNAME(String APPNAME) {
		this.APPNAME = APPNAME == null ? null : APPNAME.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.VERSIONCODE
	 * @return  the value of CPMOMS.APP_USER.VERSIONCODE
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public String getVERSIONCODE() {
		return VERSIONCODE;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.VERSIONCODE
	 * @param VERSIONCODE  the value for CPMOMS.APP_USER.VERSIONCODE
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setVERSIONCODE(String VERSIONCODE) {
		this.VERSIONCODE = VERSIONCODE == null ? null : VERSIONCODE.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.OSTYPE
	 * @return  the value of CPMOMS.APP_USER.OSTYPE
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public String getOSTYPE() {
		return OSTYPE;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.OSTYPE
	 * @param OSTYPE  the value for CPMOMS.APP_USER.OSTYPE
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setOSTYPE(String OSTYPE) {
		this.OSTYPE = OSTYPE == null ? null : OSTYPE.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.IPADDRESS
	 * @return  the value of CPMOMS.APP_USER.IPADDRESS
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public String getIPADDRESS() {
		return IPADDRESS;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.IPADDRESS
	 * @param IPADDRESS  the value for CPMOMS.APP_USER.IPADDRESS
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setIPADDRESS(String IPADDRESS) {
		this.IPADDRESS = IPADDRESS == null ? null : IPADDRESS.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.CREATE_DATE
	 * @return  the value of CPMOMS.APP_USER.CREATE_DATE
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public Date getCREATE_DATE() {
		return CREATE_DATE;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.CREATE_DATE
	 * @param CREATE_DATE  the value for CPMOMS.APP_USER.CREATE_DATE
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setCREATE_DATE(Date CREATE_DATE) {
		this.CREATE_DATE = CREATE_DATE;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.LASTLOGIN
	 * @return  the value of CPMOMS.APP_USER.LASTLOGIN
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public Date getLASTLOGIN() {
		return LASTLOGIN;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.LASTLOGIN
	 * @param LASTLOGIN  the value for CPMOMS.APP_USER.LASTLOGIN
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setLASTLOGIN(Date LASTLOGIN) {
		this.LASTLOGIN = LASTLOGIN;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.STATUS
	 * @return  the value of CPMOMS.APP_USER.STATUS
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public String getSTATUS() {
		return STATUS;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.STATUS
	 * @param STATUS  the value for CPMOMS.APP_USER.STATUS
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setSTATUS(String STATUS) {
		this.STATUS = STATUS == null ? null : STATUS.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.NICK_NAME
	 * @return  the value of CPMOMS.APP_USER.NICK_NAME
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public String getNICK_NAME() {
		return NICK_NAME;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.NICK_NAME
	 * @param NICK_NAME  the value for CPMOMS.APP_USER.NICK_NAME
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setNICK_NAME(String NICK_NAME) {
		this.NICK_NAME = NICK_NAME == null ? null : NICK_NAME.trim();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.MOD_TIME
	 * @return  the value of CPMOMS.APP_USER.MOD_TIME
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public Date getMOD_TIME() {
		return MOD_TIME;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.MOD_TIME
	 * @param MOD_TIME  the value for CPMOMS.APP_USER.MOD_TIME
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setMOD_TIME(Date MOD_TIME) {
		this.MOD_TIME = MOD_TIME;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method returns the value of the database column CPMOMS.APP_USER.OPERUSER
	 * @return  the value of CPMOMS.APP_USER.OPERUSER
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public String getOPERUSER() {
		return OPERUSER;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method sets the value of the database column CPMOMS.APP_USER.OPERUSER
	 * @param OPERUSER  the value for CPMOMS.APP_USER.OPERUSER
	 * @ibatorgenerated  Mon Oct 22 17:03:25 CST 2012
	 */
	public void setOPERUSER(String OPERUSER) {
		this.OPERUSER = OPERUSER == null ? null : OPERUSER.trim();
	}
	
}